# Generated by Django 4.2.25 on 2025-12-13 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_school_background_color_school_button_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPublicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Usa solo números, opcional +')])),
                ('email_public', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('schedule_text', models.CharField(blank=True, max_length=250)),
                ('map_iframe', models.TextField(blank=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_config', to='myapp.school')),
            ],
            options={
                'verbose_name': 'Config sitio público',
                'verbose_name_plural': 'Config sitios públicos',
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/news/')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='myapp.school')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/blocks/')),
                ('button_text', models.CharField(blank=True, max_length=60)),
                ('button_url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_blocks', to='myapp.school')),
            ],
            options={
                'verbose_name': 'Bloque Home',
                'verbose_name_plural': 'Bloques Home',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='public/banners/')),
                ('content', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=60)),
                ('cta_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_pages', to='myapp.school')),
            ],
            options={
                'verbose_name': 'Página pública',
                'verbose_name_plural': 'Páginas públicas',
                'unique_together': {('school', 'slug')},
            },
        ),
    ]
