# Generated by Django 4.2.25 on 2025-12-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_school_background_color_school_button_color_and_more'),
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public/hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='myapp.school')),
            ],
            options={
                'verbose_name': 'Slide Hero (Home)',
                'verbose_name_plural': 'Slides Hero (Home)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
