# Generated by Django 4.2.25 on 2025-12-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_school_background_color_school_button_color_and_more'),
        ('sitio', '0002_homeheroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título (opcional)')),
                ('image', models.ImageField(upload_to='about/slides/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_slides', to='myapp.school')),
            ],
            options={
                'verbose_name': 'Slide Nosotros',
                'verbose_name_plural': 'Slides Nosotros',
                'ordering': ['order'],
            },
        ),
    ]
