# Generated by Django 4.2.25 on 2025-12-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_aboutslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpage',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='public/videos/'),
        ),
        migrations.AddField(
            model_name='publicpage',
            name='hero_video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/videos/posters/'),
        ),
    ]
