# Generated by Django 4.2.25 on 2025-12-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_school_background_color_school_button_color_and_more'),
        ('tablero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.school'),
            preserve_default=False,
        ),
    ]
