# Generated by Django 4.2.25 on 2025-10-31 16:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Año lectivo',
                'verbose_name_plural': 'Años lectivos',
                'ordering': ['-activo', '-nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignaturaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('area', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Asignatura (Catálogo)',
                'verbose_name_plural': 'Asignaturas (Catálogo)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignaturaOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidad_horaria', models.PositiveIntegerField(default=0)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='academico.aniolectivo')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='academico.asignaturacatalogo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='academico.curso')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente')),
            ],
            options={
                'ordering': ['anio__nombre', 'curso__grado', 'curso__nombre', 'asignatura__nombre'],
                'unique_together': {('anio', 'curso', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nombre', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='academico.aniolectivo')),
            ],
            options={
                'ordering': ['anio__nombre', 'numero'],
                'unique_together': {('anio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Porcentaje dentro del periodo. La suma por periodo debe ser 100%.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='academico.asignaturaoferta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='academico.periodo')),
            ],
            options={
                'ordering': ['oferta__anio__nombre', 'oferta__curso__grado', 'oferta__asignatura__nombre', 'periodo__numero', 'titulo'],
                'unique_together': {('oferta', 'periodo', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_logro', to='academico.estudiante')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.logro')),
            ],
            options={
                'unique_together': {('estudiante', 'logro')},
                'index_together': {('estudiante', 'logro')},
            },
        ),
    ]
