# Generated by Django 4.2.25 on 2025-11-07 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0002_aniolectivo_asignaturacatalogo_asignaturaoferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Observador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('POSITIVA', 'Positiva'), ('LLAMADO', 'Llamado de atención'), ('ACUERDO', 'Acuerdo con acudiente')], max_length=40)),
                ('detalle', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='academico.estudiante')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
