# Generated by Django 4.2.25 on 2025-11-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_docente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionBoletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_boletin', to='academico.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_boletin', to='academico.periodo')),
            ],
            options={
                'verbose_name': 'Observación de boletín',
                'verbose_name_plural': 'Observaciones de boletín',
                'unique_together': {('estudiante', 'periodo')},
            },
        ),
    ]
