# Generated by Django 4.2.25 on 2025-11-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_estudiante_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='docentes/'),
        ),
    ]
