# Generated by Django 4.2.25 on 2025-11-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_docente_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaseLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aniolectivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('docente', models.ForeignKey(blank=True, help_text='Docente que pasó la asistencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodo')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('curso', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Ausencia justificada'), ('T', 'Tardanza')], default='P', max_length=1)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
                ('pase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='academico.paselista')),
            ],
            options={
                'ordering': ['estudiante__apellidos', 'estudiante__nombres'],
                'unique_together': {('pase', 'estudiante')},
            },
        ),
    ]
