# Generated by Django 4.2.25 on 2025-12-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('es_receso', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Receso, Almuerzo, Actividad lúdica', max_length=100)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to='academico.aniolectivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to='academico.curso')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_horario', to='academico.asignaturaoferta')),
            ],
            options={
                'verbose_name': 'Bloque de horario',
                'verbose_name_plural': 'Bloques de horario',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
