# Generated by Django 4.2.25 on 2025-12-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_bloquehorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('CC', 'Cédula de ciudadanía')], default='RC', max_length=2, verbose_name='Tipo de documento'),
        ),
    ]
