# Generated by Django 4.2.25 on 2025-12-04 14:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_estudiante_tipo_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logro',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='logro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='logro',
            name='tipo',
            field=models.CharField(choices=[('HACER', 'Saber hacer'), ('SER', 'Saber ser'), ('SABER', 'Saber')], default='HACER', help_text='Clasificación: saber hacer / saber ser / saber.', max_length=10),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Porcentaje dentro del logro. Lo normal es que las actividades sumen 100%.', max_digits=5)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.logro')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
            options={
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
    ]
