# Generated by Django 4.2.25 on 2025-12-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_alter_logro_options_alter_logro_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaberSer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aniolectivo')),
                ('asignatura_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignaturaoferta')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodo')),
            ],
            options={
                'unique_together': {('estudiante', 'periodo', 'asignatura_oferta')},
            },
        ),
    ]
