# Generated by Django 4.2.25 on 2025-12-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_saberser'),
    ]

    operations = [
        migrations.AddField(
            model_name='saberser',
            name='nota_autoevaluacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='saberser',
            name='nota_comportamiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='saberser',
            name='nota_responsabilidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
