# Generated by Django 4.2.25 on 2025-12-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_school_background_color_school_button_color_and_more'),
        ('academico', '0014_saberser_nota_autoevaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturacatalogo',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaturaoferta',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logro',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observador',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paselista',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.school'),
            preserve_default=False,
        ),
    ]
