# Generated by Django 4.2.25 on 2025-12-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del colegio')),
                ('domain', models.CharField(help_text='Ej: giongabi.edu.co, 127.0.0.1, localhost', max_length=200, unique=True, verbose_name='Dominio')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#0055AA', help_text='Ej: #0055AA', max_length=20, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#FFFFFF', help_text='Ej: #FFFFFF', max_length=20, verbose_name='Color secundario')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
            },
        ),
    ]
