# Generated by Django 4.2.25 on 2025-12-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='background_color',
            field=models.CharField(default='#F4F8F6', max_length=20, verbose_name='Color de fondo'),
        ),
        migrations.AddField(
            model_name='school',
            name='button_color',
            field=models.CharField(default='#00695C', max_length=20, verbose_name='Color de botones'),
        ),
        migrations.AddField(
            model_name='school',
            name='mission',
            field=models.TextField(blank=True, verbose_name='Misión'),
        ),
        migrations.AddField(
            model_name='school',
            name='slogan',
            field=models.CharField(blank=True, help_text='Ej: EDUCANDO CON AMOR A QUIENES CONSTRUIRÁN EL MAÑANA', max_length=300, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='school',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Visión'),
        ),
        migrations.AlterField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#0055AA', max_length=20, verbose_name='Color primario'),
        ),
        migrations.AlterField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', max_length=20, verbose_name='Color secundario'),
        ),
    ]
