# Generated by Django 4.2.25 on 2025-12-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_school_background_color_school_button_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sello',
            field=models.ImageField(blank=True, help_text='Sello oficial para certificados (marca de agua o firma)', null=True, upload_to='sellos/', verbose_name='Sello institucional'),
        ),
    ]
