# Generated by Django 4.2.25 on 2025-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptopago',
            name='bloquea_boletin',
            field=models.BooleanField(default=True, help_text='Si hay deuda vencida de este concepto, bloquea el boletín del estudiante.'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='mes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
