# Generated by Django 4.2.25 on 2025-12-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_school_sello'),
        ('cartera', '0002_conceptopago_bloquea_boletin_cuentaporcobrar_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anioeconomico',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anios_economicos', to='myapp.school'),
        ),
        migrations.AddField(
            model_name='conceptopago',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_pago', to='myapp.school'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_cobrar', to='myapp.school'),
        ),
        migrations.AddField(
            model_name='pago',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='myapp.school'),
        ),
    ]
