# Generated by Django 4.2.25 on 2025-12-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_school_background_color_school_button_color_and_more'),
        ('cuentas', '0002_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='myapp.school'),
        ),
    ]
